name: Android Build and Export

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Install React Native Dependencies
        run: |
          yarn install --immutable
          git status

      - name: Build Workspace
        run: |
          yarn lerna run build

      - name: Build Android App
        working-directory: ./packages/legacy/app/android
        run: |
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: packages/legacy/app/android/app/build/outputs/apk/release/app-release.apk

      - name: Build Android App Bundle
        working-directory: ./packages/legacy/app/android
        run: |
          ./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-bundle
          path: packages/legacy/app/android/app/build/outputs/bundle/release/app-release.aab
