name: iOS Build and Export

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./packages/legacy/app

      - name: Cache pod dependencies
        uses: actions/cache@v3
        with:
          path: packages/legacy/app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install React Native Dependencies
        run: |
          yarn install --immutable
          git status

      - name: Build Workspace
        run: |
          yarn lerna run build

      - name: Install iOS dependencies
        working-directory: ./packages/legacy/app
        run: |
          yarn run ios:setup
          git status
          git diff ios/Podfile.lock

      - name: Build iOS App
        working-directory: ./packages/legacy/app/ios
        run: |
          xcodebuild -workspace AriesBifold.xcworkspace \
                     -scheme AriesBifold \
                     -configuration Release \
                     -derivedDataPath build \
                     -archivePath build/AriesBifold.xcarchive \
                     -allowProvisioningUpdates \
                     archive

      - name: Export IPA
        working-directory: ./packages/legacy/app/ios
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/AriesBifold.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build/AriesBifold.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ipa-file
          path: packages/legacy/app/ios/build/AriesBifold.ipa
